#How to publish on Docker HUB
# 1) docker build -t vaimeedock/sepa:latest -f Dockerfile .
# 2) docker login -u YOUR-USER-NAME.
# Build command on Apple M1: docker buildx build --platform linux/amd64 --push -t vaimeedock/jmx-test .

FROM openjdk:20-jdk-oraclelinux7
#FROM openjdk:17

COPY ./jmxproxy-3.4.0.jar /jmx.jar
COPY ./config.yml /config.yml

EXPOSE 8123

ENTRYPOINT ["java","-jar","jmx.jar","server","config.yml"]
